accounts/urls.py
from django.conf.urls import url
from .views import LoginView, LogoutView, CreateUser, ProfileView, UpdateProfile, search_user

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^signup/$', CreateUser.as_view(), name="signup"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^profile/(?P<id>\d+)$', ProfileView.as_view(), name="profile"),
    url(r'^(?P<id>\d+)/update_profile$', UpdateProfile.as_view(), name="update_profile"),

    url(r'^ajax/user_search/$', search_user, name='search_user'),
]

local_stack_overflow/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('questionnaire.urls', namespace='question')),
    url(r'^users/', include('accounts.urls', namespace='accounts')),
    url(r'^markdownx/', include('markdownx.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

questionnaire/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from .views import QuestionList, TagList, UserList, QuestionListByTag, QuestionDetail, current_answer, CommentAddAnswer, \
    CommentAddQuestion, AddQuestionView, user_like, search_tag, ActionListView
from .api_views import QuestionViewSet, AnswerViewSet, TagViewSet, CommentViewSet, ProfileViewSet, UserViewSet


router = DefaultRouter()
router.register(r'question', QuestionViewSet)
router.register(r'answer', AnswerViewSet)
router.register(r'tag', TagViewSet)
router.register(r'comment', CommentViewSet)
router.register(r'profile', ProfileViewSet)
router.register(r'user', UserViewSet)

urlpatterns = [
    url(r'^$', QuestionList.as_view(), name="home_page"),
    url(r'^tags/$', TagList.as_view(), name="tags"),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', QuestionListByTag.as_view(), name="tag_detail"),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', QuestionDetail.as_view(), name='question_detail'),
    url(r'^users/$', UserList.as_view(), name="users"),

    url(r'^add-question/$', AddQuestionView.as_view(), name="add_question"),

    url(r'^add-comment-answer/(?P<id>\d+)/$', CommentAddAnswer.as_view(), name="comment-add-answer"),
    url(r'^add-comment-question/(?P<id>\d+)/$', CommentAddQuestion.as_view(), name="comment-add-question"),

    url(r'^ajax/correct-answer/$', current_answer, name='correct_answer'),
    url(r'^ajax/like/$', user_like, name='user_like'),
    url(r'^ajax/find-tags/$', search_tag, name='find_tags'),

    url(r'api/', include(router.urls)),

    url(r'^actions/list/$', ActionListView.as_view(), name="actions_list"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.urlresolvers import reverse
from taggit.models import Tag

from questionnaire.models import Question


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    link_github = models.URLField(max_length=100, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to='profile_image/', default='profile_image/default.png')
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=('-created', )

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('accounts:profile', args=[self.user.id])

    def get_best_tags(self):
        questions = Question.objects.filter(user=self.user)
        tags = Tag.objects.filter(question__in=questions)
        best_tags = tags.annotate(same_tags=Count('name')).order_by('-same_tags')[:3]
        return best_tags


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

accounts/forms.py
from django.forms import ModelForm, DateField, DateInput
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms.extras.widgets import SelectDateWidget
from accounts.models import Profile


class DateInputField(DateInput):
    input_type = 'date'


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', )


class UpdateProfileForm(ModelForm):
    # birth_date = DateField(widget=SelectDateWidget, required=False)

    class Meta:
        model = Profile
        # fields = ('link_github', 'image', 'bio', 'location', 'birth_date')
        exclude = ['created', 'user']
        widgets = {
            'birth_date': DateInputField()
        }

accounts/views.py
from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render_to_response
from django.urls import reverse_lazy
from django.views.generic import FormView, View, CreateView, DetailView, UpdateView
from kombu.utils import json

from questionnaire.models import Question, Answer
from .forms import RegisterForm, UpdateProfileForm
from .models import User, Profile


class LoginView(FormView):
    template_name = 'accounts/base_account.html'
    form_class = AuthenticationForm
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        context['section'] = 'Login'
        return context

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)
            else:
                return HttpResponse("Inactive user.")
        else:
            return HttpResponseRedirect(settings.LOGIN_URL)


class CreateUser(CreateView):
    model = User
    template_name = 'accounts/base_account.html'
    form_class = RegisterForm
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super(CreateUser, self).get_context_data(**kwargs)
        context['section'] = 'CreateUser'
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            user = self.form_valid(form)
            login(request, user)
            return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=raw_password)
        return user


class LogoutView(View):

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(settings.LOGIN_URL)


class ProfileView(DetailView):
    template_name = 'accounts/profile.html'
    model = User
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        question_list = Question.objects.filter(user=self.object)
        context['user_question_list'] = question_list
        answer_list = Answer.objects.filter(user=self.object)
        context['user_answer_list'] = answer_list
        return context


class UpdateProfile(UpdateView):
    model = User
    fields = ['username', 'email', 'first_name', 'last_name']
    template_name = 'accounts/update_profile_form.html'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super(UpdateProfile, self).get_context_data(**kwargs)
        user = self.object
        form_class = UpdateProfileForm(data=vars(user.profile))
        context['form_profile'] = form_class
        return context

    def post(self, request, *args, **kwargs):
        user = self.get_object()
        user_profile = Profile.objects.get(user=user)
        req_file = request.FILES
        req_post = request.POST
        user_profile.bio = req_post['bio']
        if req_post['birth_date'] == '':
            user_profile.birth_date = None
        else:
            user_profile.birth_date = req_post['birth_date']
        user_profile.link_github = req_post['link_github']
        user_profile.location = req_post['location']
        if not req_file:
            user_profile.save()
        else:
            user_profile.image = req_file['image']
            user_profile.save()
        return super(UpdateProfile, self).post(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        user = self.get_object()
        return reverse_lazy('accounts:profile', kwargs={'id': user.id})


def search_user(request):
    search_value = request.GET.get('suggestion', None)
    users = User.objects.filter(username__contains=search_value)
    return render_to_response('accounts/users_find.html', {'user_list': users} )

templates/accounts/base_account.html
{% extends "base.html" %}
{% block title %}
    {% if section == 'Login' %}
        Login
        {% else %}
        Sign Up
    {% endif %}
{% endblock %}

{% block content %}

     <!-- Tab links -->
    <div class="tab">
        <a {% if section == 'Login' %}class="tablinks active" {% else %}class="tablinks"{% endif %} href="{% url "accounts:login" %}">Sign In</a>
        <a {% if section == 'CreateUser' %}class="tablinks active" {% else %}class="tablinks"{% endif %} href="{% url "accounts:signup" %}">Sign Up</a>
    </div>

    <!-- Tab content -->
    {% if section == 'Login' %}
        <div class="tabcontent">
          {% include "accounts/login.html" with form=form %}
        </div>
    {% else %}
        <div class="tabcontent">
            {% include "accounts/registration.html" with form=form %}
        </div>
    {% endif %}
{% endblock %}

templates/accounts/login.html
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Sign In"></p>
</form>

templates/accounts/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Profile: {{ user.username }}
{% endblock %}

{% block content %}
<div class="profile">
    <div class="image-user">
        <div class="avatar-card">
            <img src="{{ user.profile.image.url }}">
        </div>
    </div>
    <div class="about-user">
        <h1>{{ user.username }}
            <span>
                {{ user.questions.count }} questions,
                {{ user.answer.count }} answers
            </span>
            {% if request.user == user %}
            <span style="float: right; font-size: 1.5rem">
                <a class="orange-link" href="{% url 'accounts:update_profile' id=user.id %}" >Update</a>
                |
                <a class="orange-link" href="{% url "accounts:logout" %}">Logout</a>
            </span>
            {% endif %}
        </h1>
        {% if user.first_name and user.last_name %}
            <p><span>Full name: </span>{{ user.first_name }} {{ user.last_name }}</p>
        {% endif %}
        <p>
            <span>About me: </span>
            {% if user.profile.bio %}
                {{ user.profile.bio }}
                {% else %}
                Write about yourself in profile.
            {% endif %}
        </p>
        <i><sub>sign up{{ user.profile.created }}</sub></i>
        <div class="additional-info">
            <p>
                <img class="small-icon" src="{% static "img/mail.png" %}" alt="">
                {{ user.email }}
            </p>
            <p>
                <img class="small-icon" src="{% static "img/github.png" %}" alt="">
                {% if user.profile.link_github %}
                    <a href="{{ user.profile.link_github }}">{{ user.username }}</a>
                    {% else %}
                    You can update, add link github in profile.
                {% endif %}
            </p>
            <p>
                <img class="small-icon" src="{% static "img/location.png" %}" alt="">
                {% if user.profile.location %}
                    {{ user.profile.location }}
                    {% else %}
                    You can update, add location in profile.
                {% endif %}
            </p>
        </div>
    </div>
</div>
<div class="profile-question">
    <h2>Question({{ user.questions.count }})</h2>
    {% for user_question in user_question_list %}
        <p>
            <span class="profile_likes{% for answer in user_question.answers.all %}{% if answer.is_correct %} correct{% endif %}{% endfor %}">
                {{ user_question.users_like.count }}</span>
            <a href="{{ user_question.get_absolute_url }}">{{ user_question.title }}</a>
        </p>
    {% endfor %}
</div>
<div class="profile-answer">
    <h2>Answer({{ user.answer.count }})</h2>
    {% for user_answer in user_answer_list %}
        <p>
            <span class="profile_likes{% if user_answer.is_correct %} correct{% endif %}">
                {{ user_answer.users_like.count }}</span>
            <a href="{{ user_answer.question.get_absolute_url }}">{{ user_answer.question.title }}</a>
        </p>
    {% endfor %}
</div>

{% endblock %}

templates/accounts/registration.html
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Sign up"></p>
</form>

templates/accounts/update_profile_form.html
{% extends "base.html" %}
{% block title %}Update Profile{% endblock %}
{% block content %}
<h1>Update information about you</h1>
<form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    {{ form_profile.as_p }}
    <p><input type="submit" value="Update"></p>
</form>
{% endblock %}

templates/accounts/users_find.html
<div class="user-list-search">
   {% for user in user_list %}
        <div class="user">
            <img class="image-user-list" src="{{ user.profile.image.url }}" alt="">
            <div class="about-user-list">
                <p class="name-user"><a href="{{ user.profile.get_absolute_url }}">{{ user.username }}</a></p>
                <p class="location-user">{{ user.profile.location }}</p>
                <p class="user-tag">
                    {% for tag in user.profile.get_best_tags %}
                        <a href="{% url "question:tag_detail" tag.slug %}">{{ tag.name }}</a>
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
            </div>
        </div>
   {% endfor %}
</div>