accounts/urls.py
from django.conf.urls import url
from .views import LoginView, LogoutView, CreateUser, ProfileView, UpdateProfile, search_user

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^signup/$', CreateUser.as_view(), name="signup"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^profile/(?P<id>\d+)$', ProfileView.as_view(), name="profile"),
    url(r'^(?P<id>\d+)/update_profile$', UpdateProfile.as_view(), name="update_profile"),

    url(r'^ajax/user_search/$', search_user, name='search_user'),
]

local_stack_overflow/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('questionnaire.urls', namespace='question')),
    url(r'^users/', include('accounts.urls', namespace='accounts')),
    url(r'^markdownx/', include('markdownx.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

questionnaire/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from .views import QuestionList, TagList, UserList, QuestionListByTag, QuestionDetail, current_answer, CommentAddAnswer, \
    CommentAddQuestion, AddQuestionView, user_like, search_tag, ActionListView
from .api_views import QuestionViewSet, AnswerViewSet, TagViewSet, CommentViewSet, ProfileViewSet, UserViewSet


router = DefaultRouter()
router.register(r'question', QuestionViewSet)
router.register(r'answer', AnswerViewSet)
router.register(r'tag', TagViewSet)
router.register(r'comment', CommentViewSet)
router.register(r'profile', ProfileViewSet)
router.register(r'user', UserViewSet)

urlpatterns = [
    url(r'^$', QuestionList.as_view(), name="home_page"),
    url(r'^tags/$', TagList.as_view(), name="tags"),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', QuestionListByTag.as_view(), name="tag_detail"),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', QuestionDetail.as_view(), name='question_detail'),
    url(r'^users/$', UserList.as_view(), name="users"),

    url(r'^add-question/$', AddQuestionView.as_view(), name="add_question"),

    url(r'^add-comment-answer/(?P<id>\d+)/$', CommentAddAnswer.as_view(), name="comment-add-answer"),
    url(r'^add-comment-question/(?P<id>\d+)/$', CommentAddQuestion.as_view(), name="comment-add-question"),

    url(r'^ajax/correct-answer/$', current_answer, name='correct_answer'),
    url(r'^ajax/like/$', user_like, name='user_like'),
    url(r'^ajax/find-tags/$', search_tag, name='find_tags'),

    url(r'api/', include(router.urls)),

    url(r'^actions/list/$', ActionListView.as_view(), name="actions_list"),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "markdownx/admin/css/markdownx.min.css" %}" rel="stylesheet">
    <link href="{% static "/css/base.css" %}" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="{% static "/markdownx/js/markdownx.min.js" %}" type="text/javascript"></script>
    <script src="{% static "/js/find_user.js" %}" type="text/javascript"></script>
    <script src="{% static "/js/show-more-commet.js" %}" type="text/javascript"></script>
    <script src="{% static "/js/add-comment-show-form.js" %}" type="text/javascript"></script>
    <script src="{% static "/js/correct-answer.js" %}" type="text/javascript"></script>
    <script src="{% static "/js/user_like.js" %}" type="text/javascript"></script>
<body>

    <header>
        <a href="/"><span class="logo">Stack Overflow<sub>local</sub></span></a>
        {#{% url 'books:author_list' %}#}
        <ul class="menu">
            <li {% if section == "Question" %}class="selected"{% endif %}>
                <a href="{% url 'question:home_page' %}">Questions</a>
            </li>
            <li {% if section == "Tags" %}class="selected"{% endif %}>
                <a href="{% url 'question:tags' %}">Tags</a>
            </li>
            <li {% if section == "Users" %}class="selected"{% endif %}>
                <a href="{% url 'question:users' %}">Users</a>
            </li>
            <li {% if section == "Activity" %}class="selected"{% endif %}>
                <a href="{% url 'question:actions_list' %}">Activity</a>
            </li>
        </ul>
        <ul class="menu-right">
            {% if request.user.is_authenticated %}
                <li>
                    <img class="header-account-image" src="{{ request.user.profile.image.url }}">
                </li>
                <li>
                    <a class="orange-link" href="{{ request.user.profile.get_absolute_url }}">{{ request.user.username}}</a>
                </li>
            {% else %}
               <li>
                    <a class="login-btn" href="{% url 'accounts:login' %}">Sing In</a>
                </li>
                <li>
                    <a class="registration-btn" href="{% url 'accounts:signup' %}">Sing Up</a>
                </li>
            {% endif %}
        </ul>

    </header>

    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}"> < </a>
        {% endif %}

        <span class="current">
            {{ page.number }} of {{ page.paginator.num_pages }}
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}"> > </a>
        {% endif %}
    </span>
</div>