accounts/urls.py
from django.conf.urls import url
from .views import LoginView, LogoutView, CreateUser, ProfileView, UpdateProfile, search_user

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^signup/$', CreateUser.as_view(), name="signup"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^profile/(?P<id>\d+)$', ProfileView.as_view(), name="profile"),
    url(r'^(?P<id>\d+)/update_profile$', UpdateProfile.as_view(), name="update_profile"),

    url(r'^ajax/user_search/$', search_user, name='search_user'),
]

local_stack_overflow/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('questionnaire.urls', namespace='question')),
    url(r'^users/', include('accounts.urls', namespace='accounts')),
    url(r'^markdownx/', include('markdownx.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

questionnaire/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from .views import QuestionList, TagList, UserList, QuestionListByTag, QuestionDetail, current_answer, CommentAddAnswer, \
    CommentAddQuestion, AddQuestionView, user_like, search_tag, ActionListView
from .api_views import QuestionViewSet, AnswerViewSet, TagViewSet, CommentViewSet, ProfileViewSet, UserViewSet


router = DefaultRouter()
router.register(r'question', QuestionViewSet)
router.register(r'answer', AnswerViewSet)
router.register(r'tag', TagViewSet)
router.register(r'comment', CommentViewSet)
router.register(r'profile', ProfileViewSet)
router.register(r'user', UserViewSet)

urlpatterns = [
    url(r'^$', QuestionList.as_view(), name="home_page"),
    url(r'^tags/$', TagList.as_view(), name="tags"),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', QuestionListByTag.as_view(), name="tag_detail"),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', QuestionDetail.as_view(), name='question_detail'),
    url(r'^users/$', UserList.as_view(), name="users"),

    url(r'^add-question/$', AddQuestionView.as_view(), name="add_question"),

    url(r'^add-comment-answer/(?P<id>\d+)/$', CommentAddAnswer.as_view(), name="comment-add-answer"),
    url(r'^add-comment-question/(?P<id>\d+)/$', CommentAddQuestion.as_view(), name="comment-add-question"),

    url(r'^ajax/correct-answer/$', current_answer, name='correct_answer'),
    url(r'^ajax/like/$', user_like, name='user_like'),
    url(r'^ajax/find-tags/$', search_tag, name='find_tags'),

    url(r'api/', include(router.urls)),

    url(r'^actions/list/$', ActionListView.as_view(), name="actions_list"),
]

questionnaire/models.py
import datetime
from django.contrib.contenttypes.fields import GenericForeignKey
from django.db import models
from django.db.models import signals
from django.contrib.auth.models import User
from markdownx.utils import markdownify
from taggit.managers import TaggableManager
from django.core.urlresolvers import reverse
from django.contrib.contenttypes.models import ContentType
from taggit.models import Tag


class DescriptionTag(models.Model):
    tag = models.OneToOneField(Tag, related_name='description')
    description = models.TextField(blank=True)


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='questions')
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, db_index=True)
    text_question = models.TextField()
    tags = TaggableManager()
    users_like = models.ManyToManyField(User, related_name='question_liked', blank=True)
    # dislike
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        index_together = (('id', 'slug'),)
        ordering = ('-created', )

    @property
    def formatted_markdown(self):
        return markdownify(self.text_question)

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse('question:question_detail', args=[self.id, self.slug])


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='answer')  # I'm not sure what need on_delete
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text_answer = models.TextField()
    is_correct = models.BooleanField(default=False)
    users_like = models.ManyToManyField(User, related_name='answer_liked', blank=True)
    # dislike
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        # ordering = ('-is_correct', '-created',)
        ordering = ('-created',)

    def __str__(self):
        return self.text_answer

    @property
    def formatted_markdown(self):
        return markdownify(self.text_answer)


def send_email_question_user(sender, instance, signal, *args, **kwargs):
    from .tasks import send_message
    created = kwargs.get('created')
    if created:
        send_message.delay(instance.pk)


signals.post_save.connect(send_email_question_user, sender=Answer)


class Comment(models.Model):
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    user = models.ForeignKey(User, related_name='comments')
    comment = models.TextField(max_length=400)
    added_at = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        ordering = ('added_at',)


def parse_stack_description_tag(sender, instance, signal, *args, **kwargs):
    DescriptionTag.objects.create(tag=instance)


signals.post_save.connect(parse_stack_description_tag, sender=Tag)

questionnaire/forms.py
from django.forms import ModelForm
from markdownx.fields import MarkdownxFormField

from questionnaire.models import Answer, Comment, Question


class AnswerForm(ModelForm):
    text_answer = MarkdownxFormField()

    class Meta:
        model = Answer
        fields = ('text_answer', )


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ('comment', )


class AddQuestion(ModelForm):
    text_question = MarkdownxFormField()

    class Meta:
        model = Question
        fields = ('title', 'text_question', 'tags', )

questionnaire/views.py
from actstream.models import Action
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.db.models import Count
from django.shortcuts import redirect, render_to_response
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin, CreateView
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from questionnaire.forms import AnswerForm, CommentForm, AddQuestion
from .models import Question, Answer, Comment
from taggit.models import Tag
from actstream import action


class QuestionList(ListView):
    template_name = 'questionnaire/question_list.html'
    model = Question
    paginate_by = 15

    def get_context_data(self, **kwargs):
        context = super(QuestionList, self).get_context_data(**kwargs)
        context['section'] = 'Question'
        return context


class TagList(ListView):
    template_name = 'questionnaire/tag_list.html'
    model = Tag
    paginate_by = 100

    def get_queryset(self):
        return Tag.objects.all().annotate(
            total_use=Count('taggit_taggeditem_items')
        ).order_by('-total_use')

    def get_context_data(self, **kwargs):
        context = super(TagList, self).get_context_data(**kwargs)
        context['section'] = 'Tags'
        return context


class UserList(ListView):
    template_name = 'questionnaire/user_list.html'
    model = User
    paginate_by = 36

    def get_queryset(self):
        return User.objects.all().annotate(
            total_question=Count('questions')
        ).order_by('-total_question')

    def get_context_data(self, **kwargs):
        context = super(UserList, self).get_context_data(**kwargs)
        context['section'] = 'Users'
        return context


class QuestionListByTag(DetailView):
    template_name = 'questionnaire/tag_detail.html'
    model = Tag
    slug_url_kwarg = 'tag_slug'

    def get_context_data(self, **kwargs):
        context = super(QuestionListByTag, self).get_context_data(**kwargs)
        questions = Question.objects.filter(tags__name__in=[self.object.name])
        context['questions'] = questions
        context['section'] = 'Question'
        return context


class QuestionDetail(FormMixin, DetailView):
    template_name = 'questionnaire/question_detail.html'
    model = Question
    form_class = AnswerForm
    slug_url_kwarg = 'slug'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super(QuestionDetail, self).get_context_data(**kwargs)
        context['section'] = 'Question'
        form_comment = CommentForm()
        context['form_comment'] = form_comment

        question = self.object

        content_type = ContentType.objects.get_for_model(question)
        question_comment_list = Comment.objects.filter(
            content_type__pk=content_type.pk,
            object_id=question.pk
        )
        answers = question.answers.all()
        answers_id = [a.id for a in answers]

        content_type = ContentType.objects.get_for_model(Answer)
        answers_comment_list = Comment.objects.filter(
            content_type__pk=content_type.pk,
            object_id__in=answers_id
        )
        question_tags_ids = question.tags.values_list('id', flat=True)
        similar_question = Question.objects.filter(tags__in=question_tags_ids).exclude(id=question.id)
        similar_question = similar_question.annotate(same_tags=Count('tags')).order_by('-same_tags')[:5]
        context['similar_question'] = similar_question
        context['question_comment_list'] = question_comment_list
        context['answers_comment_list'] = answers_comment_list
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        question = self.get_object()
        user = self.request.user
        text_answer = self.request.POST.get("text_answer")
        answer = Answer.objects.create(user=user, question=question, text_answer=text_answer)
        action.send(user, verb='answered', target=answer)
        return redirect(question)


class CommentAddAnswer(DetailView, FormMixin):
    form_class = CommentForm
    model = Answer
    pk_url_kwarg = "id"

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        answer = self.get_object()
        user = self.request.user
        text_comment = self.request.POST.get('comment')
        content_type = ContentType.objects.get_for_model(answer)
        print(content_type)
        new_comment = Comment.objects.create(
            content_type=content_type,
            object_id=answer.pk,
            user=user,
            comment=text_comment
        )
        new_comment.save()
        action.send(user, verb='answer commented', target=answer)
        return redirect(answer.question)


class CommentAddQuestion(DetailView, FormMixin):
    form_class = CommentForm
    model = Question
    pk_url_kwarg = "id"

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        question = self.get_object()
        user = self.request.user
        text_comment = self.request.POST.get('comment')
        content_type = ContentType.objects.get_for_model(question)
        print(content_type)
        new_comment = Comment.objects.create(
            content_type=content_type,
            object_id=question.pk,
            user=user,
            comment=text_comment
        )
        new_comment.save()
        action.send(user, verb='question commented', target=question)
        return redirect(question)


class AddQuestionView(LoginRequiredMixin, CreateView):
    template_name = 'questionnaire/add_question.html'
    form_class = AddQuestion
    model = Question

    def form_valid(self, form):
        cl = form.cleaned_data
        tags = cl['tags']
        slug = slugify(cl['title'])
        user = self.request.user
        question = Question(user=user, slug=slug, title=cl['title'], text_question=cl['text_question'])
        question.save()
        for tag in tags:
            question.tags.add(tag)
        action.send(user, verb='asked', target=question)
        return redirect(reverse_lazy('question:question_detail', kwargs={'id': question.id, 'slug': question.slug}))


def current_answer(request):
    answer = request.GET.get('answer_id', None)
    correct = request.GET.get('correct', None)
    answer = Answer.objects.get(id=answer)
    if correct == 'true':
        answer.is_correct = True
    elif correct == 'false':
        answer.is_correct = False
    answer.save()
    data = {
        'is_correct': answer.is_correct
    }
    action.send(request.user, verb='selected correct answer', target=answer)
    return JsonResponse(data)


@login_required
@require_POST
def user_like(request):
    model_name = request.POST.get('model_name')
    id_object = request.POST.get('id')
    action_post = request.POST.get('action')
    if id_object and action_post:
        if model_name == 'question':
            question = Question.objects.get(id=id_object)
            if action_post == 'like':
                question.users_like.add(request.user)
                action.send(request.user, verb='like', target=question)
            else:
                question.users_like.remove(request.user)
        else:
            answer = Answer.objects.get(id=id_object)
            if action_post == 'like':
                answer.users_like.add(request.user)
            else:
                answer.users_like.remove(request.user)
        return JsonResponse({'status': 'ok', 'id': id_object})


def search_tag(request):
    search_value = request.GET.get('suggestion', None)
    tags = Tag.objects.filter(name__contains=search_value)
    return render_to_response('questionnaire/tag_find.html', {'tag_list': tags})


class ActionListView(ListView):
    model = Action
    template_name = 'questionnaire/actions.html'
    paginate_by = 40

    def get_context_data(self, **kwargs):
        context = super(ActionListView, self).get_context_data(**kwargs)
        context['section'] = 'Activity'
        return context

templates/questionnaire/add_question.html
{% extends "base.html" %}
{% block title %}
    Ask question
{% endblock %}

{% block content %}
    <form class="add_question" action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" value="Add" /></p>
    </form>
{% endblock %}

templates/questionnaire/latest_question.html
<ul>
{% for question in latest_question %}
    <li>
        <a href="{{ question.get_absolute_url }}">{{ question.title }}</a>
    </li>
    {% empty %}
    Not questions yet.
{% endfor %}
</ul>

templates/questionnaire/question_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}Questions{% endblock %}
{% block content %}
    {% if request.user.is_authenticated %}
    <h1 class="title-detail">
        {{ question.title }}
        <a class="ask-question-btn" href="{% url "question:add_question" %}">Ask Question</a>
    </h1>
        {% else %}
        <h2 class="need-login">Want ask question? Your need <a href="{% url "accounts:login" %}">Login</a></h2>
        <h1 class="title-detail">
            {{ question.title }}
        </h1>
    {% endif %}
    <div class="questions_list">
        <div class="question">
            <div class="statistic-question">
                <p class="tl-question">{{ question.users_like.count }}</p>
                <a href="" data-model-name="question" data-id="{{ question.id }}" data-action="{% if request.user in question.users_like.all %}un{% endif %}like"
                    class="like-question">
                    {% if request.user not in question.users_like.all %}
                        Like
                    {% else %}
                        Unlike
                    {% endif %}
                </a>
            </div>
            <div class="text-question-detail">
                <p>{{ question.formatted_markdown|safe }}</p>
                <p class="tags">
                    {% for tag in question.tags.all %}
                        <a href="{% url "question:tag_detail" tag.slug %}">
                            {{ tag.name }}
                        </a>
                    {% endfor %}
                </p>
                <div class="user-question user-detail-question">
                    <p>
                        <span class="date-question"><i>{{ question.created }}</i></span>
                        <img class="header-account-image" src="{{ question.user.profile.image.url }}" alt="">
                        <a href="{% url "accounts:profile" id=question.user.id %}">{{ question.user.username }}</a>
                    </p>
                </div>
                <p>
                    <a class="add-comment" id="q-add-comment_btn">add a comment</a>
                </p>
                <div class="comment-list" id="q-comment-list">
                    {% for comment in question_comment_list.all %}
                        <div class="comment">
                            <p>
                                {{ comment.comment }} &ndash;
                                <a href="{{ comment.user.profile.get_absolute_url }}">{{ comment.user }}</a>
                                <span class="date-comment"><i>{{ comment.added_at }}</i></span>
                            </p>
                        </div>
                    {% endfor %}
                    <a class="list-toggle" id="q-list-toggle">show more comments</a>
                </div>
                <div class="add-comment-form" id="q-comment_form">
                    {% if request.user.is_authenticated %}
                        <form action="{% url "question:comment-add-question" id=question.id %}" method="POST">
                            {% csrf_token %}
                            <p>{{ form_comment.comment }}</p>
                            <p><input type="submit" value="Post Your Comment"></p>
                        </form>
                        {% else %}
                        <h5 class="need-login center-answer">Want to comment? Your need <a href="{% url "accounts:login" %}">Login</a></h5>
                    {% endif %}
                </div>
            </div>
            {% if question.answers.count > 0 %}
                <h3 class="answer-count">{{ question.answers.count }} Answers</h3>
            {% endif %}
        </div>
    </div>

    <div class="answer-list">
        {% for answer in question.answers.all %}
        <div class="answer">
            <div class="statistic-question">
                <p class="tl-answer-{{ answer.id }}">{{ answer.users_like.count }}</p>
                <a href="" data-id="{{ answer.id }}" data-action="{% if request.user in answer.users_like.all %}un{% endif %}like"
                    class="like-answer-{{ answer.id }}">
                    {% if request.user not in answer.users_like.all %}
                        Like
                    {% else %}
                        Unlike
                    {% endif %}
                </a>
                {% if request.user == question.user or answer.is_correct %}
                    <label class="label">
                        <input  class="label__checkbox" type="checkbox" id="correct-answer" data-id="{{ answer.id }}"
                                {% if answer.is_correct %}checked{% endif %}
                                {% if request.user != question.user %}disabled{% endif %}
                        />
                        <span class="label__text">
                            <span class="label__check" {% if request.user != question.user %}style="cursor: default" {% endif %}>
                                <i class="fa fa-check icon"></i>
                            </span>
                        </span>
                    </label>
                {% endif %}
            </div>
            <div class="text-question-detail">
                <p>{{ answer.formatted_markdown|safe }}</p>
                <div class="tags">

                </div>
                <div class="user-question">
                    <p>
                        <span class="date-question"><i>{{ answer.created }}</i></span>
                        <img class="header-account-image" src="{{ answer.user.profile.image.url }}" alt="">
                        <a href="{{ answer.user.profile.get_absolute_url }}">{{ answer.user.username }}</a>
                    </p>
                </div>
                <p>
                    <a class="add-comment" id="add-comment_btn" data-id="{{ answer.id }}">add a comment</a>
                </p>
                {{ answer.comment.all }}
                <div class="comment-list" id="a-comment-list-{{ answer.id }}">
                    {% for comment in answers_comment_list.all %}
                        {% if comment.object_id == answer.id %}
                            <div class="comment">
                                <p>
                                    {{ comment.comment }} &ndash;
                                    <a href="{{ comment.user.profile.get_absolute_url }}">{{ comment.user }}</a>
                                    <span class="date-comment"><i>{{ comment.added_at }}</i></span>
                                </p>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <a class="list-toggle" id="a-list-toggle-{{ answer.id }}" data-id="{{ answer.id }}">show more comments</a>
                </div>
                <div class="add-comment-form" id="comment_form-{{ answer.id }}">
                    {% if request.user.is_authenticated %}
                        <form action="{% url "question:comment-add-answer" id=answer.id %}" method="POST">
                            {% csrf_token %}
                            <p>{{ form_comment.comment }}</p>
                            <p><input type="submit" value="Post Your Comment"></p>
                        </form>
                        {% else %}
                        <h5 class="need-login center-answer">Want to comment? Your need <a href="{% url "accounts:login" %}">Login</a></h5>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
        {% if request.user.is_authenticated %}
            {% if request.user != question.user %}
                <form class="add_question" action="" method="POST">{% csrf_token %}
                    <h2>Your Answer</h2>
                    {% for field in form %}
                        <p>{{ field }}</p>
                    {% endfor %}
                    <p><input type="submit" value="Post Your Answer"></p>
                </form>
            {% endif %}
            {% else %}
            <h2 class="need-login center-answer">Want to answer? Your need <a href="{% url "accounts:login" %}">Login</a></h2>
        {% endif %}
    </div>
    {% include "questionnaire/similar_post.html" with similar_question=similar_question %}
{% endblock %}

templates/questionnaire/question_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}Questions{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        <a class="ask-question-btn" href="{% url "question:add_question" %}">Ask Question</a>
        {% else %}
        <h3>Want ask question? Your need <a href="{% url "accounts:login" %}">Login</a></h3>
    {% endif %}
    <div class="questions_list">
    {% for question in question_list %}
        <div class="question">

            <div class="statistic-question">
                <div class="votes-stat">
                    <p>{{ question.users_like.count }}</p>
                    <span>Votes</span>
                </div>
                <div class="answers-stat{% for answer in question.answers.all %}{% if answer.is_correct %} green-answer{% endif %}{% endfor %}">
                    <p>{{ question.answers.count }}</p>
                    <span>Answers</span>
                </div>
            </div>
            <div class="text-question">
                <p><a class="orange-link" href="{{ question.get_absolute_url }}">{{ question.title }}</a></p>
                <p>{{ question.text_question|truncatechars:300}}</p>
                <p class="tags">
                    {% for tag in question.tags.all %}
                        <a href="{% url "question:tag_detail" tag.slug %}">
                            {{ tag.name }}
                        </a>
                    {% endfor %}
                </p>
                <div class="user-question">
                    <p>
                        <span class="date-question"><i>{{ question.created }}</i></span>
                        <img class="header-account-image" src="{{ question.user.profile.image.url }}" alt="">
                        <a href="{{ question.user.profile.get_absolute_url }}">{{ question.user.username }}</a>
                    </p>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
    {% include 'questionnaire/slidebar.html' %}
        {% if page_obj %}
            {% include "pagination.html" with page=page_obj %}
        {% endif %}
{% endblock %}

templates/questionnaire/slidebar.html
{% load my_tags %}
<div class="slidebar">
    <h1>{% total_question %}<sub> question</sub></h1>
    <h3>Latest questions</h3>
    {% show_latest_question 3 %}
    <h3>Most answer questions</h3>
    {% get_most_answer_question as most_answer_question %}
    <ul>
    {% for question in most_answer_question %}
        <li>
            <a href="{{ question.get_absolute_url }}">{{ question.title }}</a>
        </li>
        {% empty %}
        On questions don't have answers yet.
    {% endfor %}
    </ul>
    <h3>Popular Tags</h3>
    {% get_most_taggit as related_tag %}
    <ul>
        {% for tag in related_tag %}
                <li class="tags"><a href="{% url "question:tag_detail" tag.slug %}">{{ tag.name }}</a>x {{ tag.taggit_taggeditem_items.count }}</li>
        {% empty %}
        Not tags yet.
        {% endfor %}
    </ul>
</div>

templates/questionnaire/tag_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}tagged with "{{ tag.name }}"{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
    <h2 class="title-detail">
        Questions tagged with "{{ tag.name }}"
        <a class="ask-question-btn" href="{% url "question:add_question" %}">Ask Question</a>
    </h2>
        {% else %}
        <h2 class="need-login">Want ask question? Your need <a href="{% url "accounts:login" %}">Login</a></h2>
        <h2 class="title-detail">
            Questions tagged with "{{ tag.name }}"
        </h2>
    {% endif %}
    <div class="questions_list">
    {% for question in questions %}
        <div class="question">
            <div class="statistic-question">
                <div class="votes-stat">
                    <p>{{ question.users_like.count }}</p>
                    <span>Votes</span>
                </div>
                <div class="answers-stat
                {% for answer in question.answers.all %}
                    {% if answer.is_correct %}
                        green-answer
                    {% endif %}
                {% endfor %}
                ">
                    <p>{{ question.answers.count }}</p>
                    <span>Answers</span>
                </div>
{#                <div class="answers-stat">#}
{#                    <p>{{ question.answers.count }}</p>#}
{#                    <span>Answers</span>#}
{#                </div>#}
            </div>
            <div class="text-question">
                <p><a class="orange-link" href="{{ question.get_absolute_url }}">{{ question.title }}</a></p>
                <p>{{ question.text_question|truncatechars:300}}</p>
                <p class="tags">
                    {% for tag in question.tags.all %}
                        <a href="{% url "question:tag_detail" tag.slug %}">
                            {{ tag.name }}
                        </a>
                    {% endfor %}
                </p>
                <div class="user-question">
                    <p>
                        <span class="date-question"><i>{{ question.created }}</i></span>
                        <img class="header-account-image" src="{{ question.user.profile.image.url }}" alt="">
                        <a href="{% url "accounts:profile" id=question.user.id %}">{{ question.user.username }}</a>
                    </p>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
    {% include 'questionnaire/slidebar.html' %}
    {% if page_obj %}
        {% include "pagination.html" with page=page_obj %}
    {% endif %}
{% endblock %}

templates/questionnaire/tag_find.html
<div class="tags-list-search">
    {% for tag in tag_list %}
        <div class="tag">
            <a href="{% url "question:tag_detail" tag.slug %}">
                {{ tag.name }}
            </a>
            <span class="tag_info"> x {{ tag.taggit_taggeditem_items.count }}</span>
            <p class="tag_info-main">{{ tag.description.description }}</p>
        </div>
    {% endfor %}
</div>

templates/questionnaire/tag_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}Tags{% endblock %}

{% block content %}
    <h1>Tags</h1>
    <p class="tag_info">A tag is a keyword or label that categorizes your question with other, similar questions. Using the right tags makes it easier for others to find and answer your question. </p>
    <form>
        <p><input class="search-query span10" type="text" name="suggestion" value="" id="suggestion" data-target="tag" placeholder="Find tag"/></p>
    </form>
    <div class="container">
        <div class="tags-list">
            {% for tag in tag_list %}
                <div class="tag">
                    <a href="{% url "question:tag_detail" tag.slug %}">
                        {{ tag.name }}
                    </a>
                    <span class="tag_info"> x {{ tag.taggit_taggeditem_items.count }}</span>
                    <p class="tag_info-main">{{ tag.description.description }}</p>
                </div>
            {% endfor %}
        </div>
        <div class="search_result">

        </div>
    </div>
    {% if page_obj %}
        {% include "pagination.html" with page=page_obj %}
    {% endif %}
{% endblock %}